// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpc_get_game_by_id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGameByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int64 `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *GetGameByIDRequest) Reset() {
	*x = GetGameByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_game_by_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDRequest) ProtoMessage() {}

func (x *GetGameByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_game_by_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDRequest.ProtoReflect.Descriptor instead.
func (*GetGameByIDRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_game_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetGameByIDRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type GetGameByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *GetGameByIDResponse) Reset() {
	*x = GetGameByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_game_by_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDResponse) ProtoMessage() {}

func (x *GetGameByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_game_by_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDResponse.ProtoReflect.Descriptor instead.
func (*GetGameByIDResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_game_by_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameByIDResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

var File_rpc_get_game_by_id_proto protoreflect.FileDescriptor

var file_rpc_get_game_by_id_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x62,
	0x79, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0a,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x6c, 0x61,
	0x74, 0x6f, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x73, 0x73, 0x65, 0x72, 0x74,
	0x65, 0x64, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_get_game_by_id_proto_rawDescOnce sync.Once
	file_rpc_get_game_by_id_proto_rawDescData = file_rpc_get_game_by_id_proto_rawDesc
)

func file_rpc_get_game_by_id_proto_rawDescGZIP() []byte {
	file_rpc_get_game_by_id_proto_rawDescOnce.Do(func() {
		file_rpc_get_game_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_get_game_by_id_proto_rawDescData)
	})
	return file_rpc_get_game_by_id_proto_rawDescData
}

var file_rpc_get_game_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_game_by_id_proto_goTypes = []interface{}{
	(*GetGameByIDRequest)(nil),  // 0: pb.GetGameByIDRequest
	(*GetGameByIDResponse)(nil), // 1: pb.GetGameByIDResponse
	(*Game)(nil),                // 2: pb.Game
}
var file_rpc_get_game_by_id_proto_depIdxs = []int32{
	2, // 0: pb.GetGameByIDResponse.game:type_name -> pb.Game
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_game_by_id_proto_init() }
func file_rpc_get_game_by_id_proto_init() {
	if File_rpc_get_game_by_id_proto != nil {
		return
	}
	file_game_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_get_game_by_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_game_by_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_get_game_by_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_game_by_id_proto_goTypes,
		DependencyIndexes: file_rpc_get_game_by_id_proto_depIdxs,
		MessageInfos:      file_rpc_get_game_by_id_proto_msgTypes,
	}.Build()
	File_rpc_get_game_by_id_proto = out.File
	file_rpc_get_game_by_id_proto_rawDesc = nil
	file_rpc_get_game_by_id_proto_goTypes = nil
	file_rpc_get_game_by_id_proto_depIdxs = nil
}
