// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpc_play_dessert.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayDessertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerGameId int64   `protobuf:"varint,1,opt,name=player_game_id,json=playerGameId,proto3" json:"player_game_id,omitempty"`
	DessertName  string  `protobuf:"bytes,2,opt,name=dessert_name,json=dessertName,proto3" json:"dessert_name,omitempty"`
	CardIds      []int64 `protobuf:"varint,3,rep,packed,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
}

func (x *PlayDessertRequest) Reset() {
	*x = PlayDessertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_play_dessert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayDessertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayDessertRequest) ProtoMessage() {}

func (x *PlayDessertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_play_dessert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayDessertRequest.ProtoReflect.Descriptor instead.
func (*PlayDessertRequest) Descriptor() ([]byte, []int) {
	return file_rpc_play_dessert_proto_rawDescGZIP(), []int{0}
}

func (x *PlayDessertRequest) GetPlayerGameId() int64 {
	if x != nil {
		return x.PlayerGameId
	}
	return 0
}

func (x *PlayDessertRequest) GetDessertName() string {
	if x != nil {
		return x.DessertName
	}
	return ""
}

func (x *PlayDessertRequest) GetCardIds() []int64 {
	if x != nil {
		return x.CardIds
	}
	return nil
}

type PlayDessertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DessertPlayedId int64       `protobuf:"varint,1,opt,name=dessert_played_id,json=dessertPlayedId,proto3" json:"dessert_played_id,omitempty"`
	PlayerGame      *PlayerGame `protobuf:"bytes,2,opt,name=player_game,json=playerGame,proto3" json:"player_game,omitempty"`
	GameOver        bool        `protobuf:"varint,3,opt,name=game_over,json=gameOver,proto3" json:"game_over,omitempty"`
}

func (x *PlayDessertResponse) Reset() {
	*x = PlayDessertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_play_dessert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayDessertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayDessertResponse) ProtoMessage() {}

func (x *PlayDessertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_play_dessert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayDessertResponse.ProtoReflect.Descriptor instead.
func (*PlayDessertResponse) Descriptor() ([]byte, []int) {
	return file_rpc_play_dessert_proto_rawDescGZIP(), []int{1}
}

func (x *PlayDessertResponse) GetDessertPlayedId() int64 {
	if x != nil {
		return x.DessertPlayedId
	}
	return 0
}

func (x *PlayDessertResponse) GetPlayerGame() *PlayerGame {
	if x != nil {
		return x.PlayerGame
	}
	return nil
}

func (x *PlayDessertResponse) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

var File_rpc_play_dessert_proto protoreflect.FileDescriptor

var file_rpc_play_dessert_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x64, 0x65, 0x73, 0x73, 0x65,
	0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x11, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x78, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x44, 0x65, 0x73, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64,
	0x65, 0x73, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x73, 0x65, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x07, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x13, 0x50, 0x6c,
	0x61, 0x79, 0x44, 0x65, 0x73, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x11, 0x64, 0x65, 0x73, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x64, 0x65,
	0x73, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x49, 0x64, 0x12, 0x2f, 0x0a,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x6c, 0x61, 0x74, 0x6f, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x73, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x2f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rpc_play_dessert_proto_rawDescOnce sync.Once
	file_rpc_play_dessert_proto_rawDescData = file_rpc_play_dessert_proto_rawDesc
)

func file_rpc_play_dessert_proto_rawDescGZIP() []byte {
	file_rpc_play_dessert_proto_rawDescOnce.Do(func() {
		file_rpc_play_dessert_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_play_dessert_proto_rawDescData)
	})
	return file_rpc_play_dessert_proto_rawDescData
}

var file_rpc_play_dessert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_play_dessert_proto_goTypes = []interface{}{
	(*PlayDessertRequest)(nil),  // 0: pb.PlayDessertRequest
	(*PlayDessertResponse)(nil), // 1: pb.PlayDessertResponse
	(*PlayerGame)(nil),          // 2: pb.PlayerGame
}
var file_rpc_play_dessert_proto_depIdxs = []int32{
	2, // 0: pb.PlayDessertResponse.player_game:type_name -> pb.PlayerGame
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_play_dessert_proto_init() }
func file_rpc_play_dessert_proto_init() {
	if File_rpc_play_dessert_proto != nil {
		return
	}
	file_player_game_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_play_dessert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayDessertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_play_dessert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayDessertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_play_dessert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_play_dessert_proto_goTypes,
		DependencyIndexes: file_rpc_play_dessert_proto_depIdxs,
		MessageInfos:      file_rpc_play_dessert_proto_msgTypes,
	}.Build()
	File_rpc_play_dessert_proto = out.File
	file_rpc_play_dessert_proto_rawDesc = nil
	file_rpc_play_dessert_proto_goTypes = nil
	file_rpc_play_dessert_proto_depIdxs = nil
}
