services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=bluecomet
      - POSTGRES_DB=desserted
    ports:
      - "5433:5432" #Only for local development, remove this line when deploying to AWS?
    networks:
      - desserted-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
      - "9091:9090"
    environment:
      - DB_SOURCE=postgresql://root:bluecomet@postgres:5432/desserted?sslmode=disable
    networks:
      - desserted-network
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"] #Here for future, but not needed now that migration moved to main code.
    command: [ "/app/main" ]

networks:
  desserted-network: