-- Seed file for Desserted game

-- Inserting ingredient cards
INSERT INTO cards (type, name) VALUES 
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Flour'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Sugar'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Eggs'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Butter'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Vanilla'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Berries'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Cream Cheese'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Honey'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Chocolate'),
('ingredient', 'Edible Gold Leaf'),
('ingredient', 'Edible Gold Leaf'),
('ingredient', 'Edible Gold Leaf'),
('ingredient', 'Edible Gold Leaf');

-- Inserting dessert cards
INSERT INTO desserts (name, points) VALUES 
('Cake', 10),
('Pie', 15),
('Chocolate Chip Cookies', 20),
('Cheesecake', 25),
('Marble Cake', 30),
('Triple Chocolate Brownies', 35),
('Gourmet Truffles', 40),
('Raspberry Chocolate Cheesecake', 45),
('Gold Leaf Cupcakes', 50);

-- Inserting special cards
INSERT INTO cards (type, name) VALUES 
('special', 'Wildcard Ingredient'),
('special', 'Wildcard Ingredient'),
('special', 'Wildcard Ingredient'),
('special', 'Wildcard Ingredient'),
('special', 'Wildcard Ingredient'),
('special', 'Wildcard Ingredient'),
('special', 'Wildcard Ingredient'),
('special', 'Wildcard Ingredient'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Steal Card'),
('special', 'Double Points'),
('special', 'Double Points'),
('special', 'Double Points'),
('special', 'Refresh Pantry'),
('special', 'Refresh Pantry'),
('special', 'Refresh Pantry'),
('special', 'Refresh Pantry'),
('special', 'Refresh Pantry'),
('special', 'Instant Bake'),
('special', 'Instant Bake'),
('special', 'Mystery Ingredient'),
('special', 'Mystery Ingredient'),
('special', 'Mystery Ingredient'),
('special', 'Mystery Ingredient'),
('special', 'Mystery Ingredient'),
('special', 'Mystery Ingredient'),
('special', 'Mystery Ingredient'),
('special', 'Sabotage'),
('special', 'Sabotage'),
('special', 'Sabotage'),
('special', 'Sabotage'),
('special', 'Glass of Milk'),
('special', 'Glass of Milk'),
('special', 'Glass of Milk'),
('special', 'Glass of Milk'),
('special', 'Glass of Milk'),
('special', 'Glass of Milk'),
('special', 'Glass of Milk');
