// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: player_game.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addPlayerToGame = `-- name: AddPlayerToGame :exec
INSERT INTO player_game (player_id, game_id) 
VALUES ($1, $2)
`

type AddPlayerToGameParams struct {
	PlayerID int64 `json:"player_id"`
	GameID   int64 `json:"game_id"`
}

func (q *Queries) AddPlayerToGame(ctx context.Context, arg AddPlayerToGameParams) error {
	_, err := q.db.ExecContext(ctx, addPlayerToGame, arg.PlayerID, arg.GameID)
	return err
}

const getPlayerGame = `-- name: GetPlayerGame :one
SELECT player_game_id, player_id, game_id, player_score, player_status FROM player_game 
WHERE player_game_id = $1
`

func (q *Queries) GetPlayerGame(ctx context.Context, playerGameID int64) (PlayerGame, error) {
	row := q.db.QueryRowContext(ctx, getPlayerGame, playerGameID)
	var i PlayerGame
	err := row.Scan(
		&i.PlayerGameID,
		&i.PlayerID,
		&i.GameID,
		&i.PlayerScore,
		&i.PlayerStatus,
	)
	return i, err
}

const isGameWon = `-- name: IsGameWon :one
SELECT EXISTS (
  SELECT 1 FROM player_game
  WHERE player_score >= 100 AND player_game_id = $1
) OR NOT EXISTS (
  SELECT 1 FROM game_deck
  WHERE game_id = $1
) AS is_game_won
`

// Check if a player has reached the winning condition
func (q *Queries) IsGameWon(ctx context.Context, playerGameID int64) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, isGameWon, playerGameID)
	var is_game_won sql.NullBool
	err := row.Scan(&is_game_won)
	return is_game_won, err
}

const listActivePlayerGames = `-- name: ListActivePlayerGames :many
SELECT player_game_id, player_id, player_game.game_id, player_score, player_status, games.game_id, status, created_by, current_turn, current_player_id, start_time, end_time FROM player_game 
INNER JOIN games ON player_game.game_id = games.game_id
WHERE player_id = $1 AND (games.status = 'active' OR games.status = 'pending')
`

type ListActivePlayerGamesRow struct {
	PlayerGameID    int64          `json:"player_game_id"`
	PlayerID        int64          `json:"player_id"`
	GameID          int64          `json:"game_id"`
	PlayerScore     sql.NullInt32  `json:"player_score"`
	PlayerStatus    sql.NullString `json:"player_status"`
	GameID_2        int64          `json:"game_id_2"`
	Status          string         `json:"status"`
	CreatedBy       int64          `json:"created_by"`
	CurrentTurn     int32          `json:"current_turn"`
	CurrentPlayerID sql.NullInt64  `json:"current_player_id"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         sql.NullTime   `json:"end_time"`
}

func (q *Queries) ListActivePlayerGames(ctx context.Context, playerID int64) ([]ListActivePlayerGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePlayerGames, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePlayerGamesRow{}
	for rows.Next() {
		var i ListActivePlayerGamesRow
		if err := rows.Scan(
			&i.PlayerGameID,
			&i.PlayerID,
			&i.GameID,
			&i.PlayerScore,
			&i.PlayerStatus,
			&i.GameID_2,
			&i.Status,
			&i.CreatedBy,
			&i.CurrentTurn,
			&i.CurrentPlayerID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerGames = `-- name: ListPlayerGames :many
SELECT player_game_id, player_id, game_id, player_score, player_status FROM player_game 
WHERE player_id = $1
`

func (q *Queries) ListPlayerGames(ctx context.Context, playerID int64) ([]PlayerGame, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerGames, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerGame{}
	for rows.Next() {
		var i PlayerGame
		if err := rows.Scan(
			&i.PlayerGameID,
			&i.PlayerID,
			&i.GameID,
			&i.PlayerScore,
			&i.PlayerStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerScore = `-- name: UpdatePlayerScore :one
UPDATE player_game 
SET player_score = $1
WHERE player_game_id = $2
RETURNING player_game_id, player_id, game_id, player_score, player_status
`

type UpdatePlayerScoreParams struct {
	PlayerScore  sql.NullInt32 `json:"player_score"`
	PlayerGameID int64         `json:"player_game_id"`
}

func (q *Queries) UpdatePlayerScore(ctx context.Context, arg UpdatePlayerScoreParams) (PlayerGame, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerScore, arg.PlayerScore, arg.PlayerGameID)
	var i PlayerGame
	err := row.Scan(
		&i.PlayerGameID,
		&i.PlayerID,
		&i.GameID,
		&i.PlayerScore,
		&i.PlayerStatus,
	)
	return i, err
}

const updatePlayerStatus = `-- name: UpdatePlayerStatus :exec
UPDATE player_game 
SET player_status = $1
WHERE player_game_id = $2
RETURNING player_game_id, player_id, game_id, player_score, player_status
`

type UpdatePlayerStatusParams struct {
	PlayerStatus sql.NullString `json:"player_status"`
	PlayerGameID int64          `json:"player_game_id"`
}

func (q *Queries) UpdatePlayerStatus(ctx context.Context, arg UpdatePlayerStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerStatus, arg.PlayerStatus, arg.PlayerGameID)
	return err
}
