name: Run unit tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:15-alpine
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: bluecomet
            POSTGRES_DB: desserted-test
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: Run migrations
      run: make migrateup_test
      working-directory: ./backend

    - name: Install PostgreSQL client
      run: sudo apt-get install postgresql-client
    
    - name: Print working directory
      run: pwd

    - name: Seed databse
      run: make seeddb_test
      working-directory: ./backend

    - name: Test
      run: make test
      working-directory: ./backend
      env:
        TOKEN_SYMMETRIC_KEY: ${{ secrets.TOKEN_SYMMETRIC_KEY }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        POSTGRES_USER: root
        POSTGRES_PASSWORD: bluecomet
        TEST_DB_NAME: desserted-test
        LOCAL_DB_PATH: ./backend/db
        

